name: Publish Chatwoot CE docker images

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    if: github.repository == 'abrarsaquib/chatwoot'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Clean Git remote
        run: |
          git remote remove origin || true
          git remote add origin https://github.com/${{ github.repository }}.git

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          provenance: false
          sbom: false
          attestation: false
          tags: |
            abrarsaquib/chat-custom:latest
            abrarsaquib/chat-custom:${{ github.sha }}
          build-args: |
            GIT_COMMIT=${{ github.sha }}