name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository   
        uses: actions/checkout@v4   

      - name: Set safe Git remote URL
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub  
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          provenance: false
          sbom: false
          tags: |
            abrarsaquib/chat-custom:latest
            abrarsaquib/chat-custom:${{ github.sha }}