name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository   
        uses: actions/checkout@v4   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Added for better build performance

      - name: Log in to Docker Hub  
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Your Docker Hub username
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Your Docker Hub access token

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: | # Corrected tag format
            ${{ secrets.DOCKERHUB_USERNAME }}/chat-custom:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/chat-custom:${{ github.sha }} # Optional: tag with commit SHA